development:
  adapter: sqlite3
  database: db/development.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: mydb
  host: localhost 
  pool: 5
  timeout: 5000


# development:
#   adapter: postgresql
#   encoding: unicode
#   database: database_name
#   pool: 2
#   username: your_username
#   password: your_password

# production:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   host: <%= ENV['DATABASE_HOST'] %>
#   database: <%= ENV['DATABASE_NAME'] %>
#   username: <%= ENV['DATABASE_USER'] %>
#   password: <%= ENV['DATABASE_PASSWORD'] %>